### ISSUE TITLE
Not restarting properly, not refreshing PATH variables

### ISSUE THREAD

**Issue by Nenkai** [KcrPL/RiiConnect24-Mail-Patcher-Windows#1]
It seems that the batch file is not restarting properly, so it cannot find the `gem` executable since cmd requires a restart to reload the path variables.

**Comment by KcrPL** [comment]
Will fix tommorow. Thanks again.

**Comment by KcrPL** [comment]
Closing this because i can't find the problem.

>:after_install_restart
cls
echo .>>%MainFolder%\requirerestart.txt
start patch.bat  `<--- The restart part.`
exit
