### ISSUE TITLE
Error trying to run mailparse.rb

### ISSUE THREAD

**Issue by MitsuhaKitsune** [KcrPL/RiiConnect24-Mail-Patcher-Windows#2]
I trying to patch my nwc24msg.cfg, but when I try to use the script it report me this error:

```
/mailparse.rb:76:in `+': BinData::Uint32be can't be coerced into Float (TypeError)
        from /mailparse.rb:76:in `block in convert_mail'
        from /mailparse.rb:70:in `each'
        from /mailparse.rb:70:in `convert_mail'
        from /mailparse.rb:103:in `<module:MailParse>'
        from /mailparse.rb:5:in `<module:SerieBot>'
        from /mailparse.rb:3:in `<main>'
```

**Comment by KcrPL** [comment]
Hi,
Please use patch.bat to patch your nwc24msg.cfg file, not mailparse.rb

**Comment by MitsuhaKitsune** [comment]
The patch.bat fails when try to retrieve the updates, it shows a error message:

> An Update server is not available

This is the reason because I launch the ruby patcher directly, finally I get this working, isn't fault of mailparse.rb, just didn't see that the patcher install a ruby gem.

After run `gem install bindata` the patcher works as intended, after it I test some features like forecast/news channels and it's working fine without errors connected to RC24, so I'm sorry for open this issue, all it's working fine now ^^

**Comment by KcrPL** [comment]
To be honest you should be using patcher to patch it because if you didn't had Ruby, it would install it for you. It makes a backup copy of nwc24msg.cfg in case if something goes wrong. Also could you please tell me if IOS Patcher works correctly and on which Windows version are you right now?

**Comment by KcrPL** [comment]
And it's ok. Make as many issues as you want to. We're here to solve problems.

**Comment by MitsuhaKitsune** [comment]
The IOS Patcher works but only when I download the zip from github if I try the powershell command:

![imagen](https://user-images.githubusercontent.com/34917786/35836343-079507a0-0ae0-11e8-829e-d2ae8010281a.png)

After download zip from https://github.com/RiiConnect24/IOS-Patcher/releases/download/v1.8.9/Windows.zip and start `patch.bat` the IOS Patcher work fine including the check for updates step.

The exception showed on powershell command are the same that throw the Mail Patcher on check for updates step.

My operating system are Windows 10 Pro x64 v1706 (Build 16299.192) up to date at this time.

**Comment by KcrPL** [comment]
I see...

I'm gonna investigate this. Thank you!

**Comment by MitsuhaKitsune** [comment]
If you need more tests or help just ask to me here

**Comment by KcrPL** [comment]
Sure, thank you :)

**Comment by KcrPL** [comment]
Also please send me your nwc24msg.cfg file to support@riiconnect24.net. I'll patch it for you!

**Comment by MitsuhaKitsune** [comment]
Sorry for the delay, I don't know why dont recive any notification.

My cfg it's sucesfully patched, I run the ruby script manually to it, now I see RiConnect24 and Wimmfi terms on Wii Settings Menu and the forecast/news channels start working again.

I have the unpatched file on a nand backup, you need the files?

**Comment by KcrPL** [comment]
If you patched it correctly, then no. You don't need to send it to me! :)
